### ISSUE TITLE
Implement user actions

### ISSUE THREAD

**Issue by talwinder50** [trustbloc/wallet-sdk#14]
Dashboard page with buttons for (2 day)

> Scan QR code
> See saved credentials
> Settings/preferences

Scan QR Code (5 days)

> Open Camera
> Scan QR Code
> Call OIDC Issuance/Presentation API based on protocol
> Show preview for issuance/presentation
> Complete action 

 See saved credentials (3 days)

> List of credentials
> Detailed view for the credential

Setting/Preferences (3 days)

> JWT/JSON-LD credentials

**Comment by rolsonquadras** [comment]
This has been implemented.
