### ISSUE TITLE
Remove PEx JWT related workaround

### ISSUE THREAD

**Issue by rolsonquadras** [trustbloc/wallet-sdk#158]
Remove PEx JWT related workaround once AFG support it. Based on TODO https://github.com/trustbloc/wallet-sdk/blob/ae3270b775cce256cb3762644933172c71c79ad7/pkg/openid4vp/openid4vp.go#L194.

**Comment by Moopli** [comment]
Was fixed in https://github.com/trustbloc/wallet-sdk/pull/203
