### ISSUE TITLE
[OpenID4CI] Support multiple proof types

### ISSUE THREAD

**Issue by rolsonquadras** [trustbloc/wallet-sdk#159]
Currently, SDK supports only JWT VCs. Based on TODO - https://github.com/trustbloc/wallet-sdk/blob/ae3270b775cce256cb3762644933172c71c79ad7/pkg/openid4ci/openid4ci.go#L226.

**Comment by Moopli** [comment]
This TODO is for the [proof](https://openid.net/specs/openid-4-verifiable-credential-issuance-1_0.html#name-proof-types) used by the OpenID4CI Client to prove possession of key material when making a Credential Request, not for the VC type.

As of now, the OpenID4CI spec only defines the `jwt` format, so no enhancement is needed here.
