### ISSUE TITLE
PEx - Remove workaround for schema validation

### ISSUE THREAD

**Issue by rolsonquadras** [trustbloc/wallet-sdk#165]
Based on TODO https://github.com/trustbloc/wallet-sdk/blob/ae3270b775cce256cb3762644933172c71c79ad7/pkg/credentialquery/credentialquery.go#L79

**Comment by Moopli** [comment]
https://github.com/trustbloc/wallet-sdk/pull/306 removed this workaround, but https://github.com/trustbloc/wallet-sdk/pull/318 put the workaround back in right away. 

On current main, this issue has TODOs here:
https://github.com/trustbloc/wallet-sdk/blob/d1e7fdc680aa3334b660ecb887b1ab7d4ce3059e/pkg/credentialquery/credentialquery.go#L83
https://github.com/trustbloc/wallet-sdk/blob/d1e7fdc680aa3334b660ecb887b1ab7d4ce3059e/pkg/openid4vp/openid4vp.go#L298
https://github.com/trustbloc/wallet-sdk/blob/d1e7fdc680aa3334b660ecb887b1ab7d4ce3059e/pkg/openid4vp/openid4vp.go#L361
