### ISSUE TITLE
Upgrade Vulnerable Libraries

### ISSUE THREAD

**Issue by biljanaLukovic** [trustbloc/wallet-sdk#651]
Upgrade all occurrences of:

github.com/consensys/gnark-crypto from 0.9.1 to 0.12.0.
github.com/btcsuite/btcd in /test/integration
golang.org/x/net](https://github.com/golang/net) from 0.15.0 to 0.17.0.
github.com/btcsuite/btcd](https://github.com/btcsuite/btcd) from 0.22.3 to 0.23.2.

**Comment by rolsonquadras** [comment]
These libraries have been upgraded.
